package gui;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.TextStyle;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import model.MySQL;
import raven.toast.Notifications;

public class AddStudentToClass extends javax.swing.JDialog {

    ClassPanel classPanel;
    private Double classPrice;
    String studentID;

    public AddStudentToClass(java.awt.Frame parent, boolean modal, ClassPanel classPanel) {
        super(parent, modal);
        initComponents();
        this.classPanel = classPanel;
        LoadDetails();
    }

    //Load Details
    private void LoadDetails() {

        int classTableRow = classPanel.jTable2.getSelectedRow();
        String classDetails = String.valueOf(classPanel.jTable2.getValueAt(classTableRow, 1));
        String teacherName = String.valueOf(classPanel.jTable2.getValueAt(classTableRow, 2));
        String SelectedStudent = classPanel.jList1.getSelectedValue();
        String subjectPrice = classPanel.subjectPriceMap.get(String.valueOf(classPanel.jTable2.getValueAt(classTableRow, 1)));

        cassNameLable.setText(classDetails);
        teacherNameLable.setText(teacherName);
        studentDetailsLable.setText(SelectedStudent);
        priceForMonthLable.setText(String.valueOf(subjectPrice));

        this.classPrice = Double.parseDouble(subjectPrice);

        String[] studentSplit = SelectedStudent.split("/");

        this.studentID = studentSplit[0].trim();

        jButton1.setEnabled(false);

    }
    //Load Details

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cassNameLable = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        teacherNameLable = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        studentDetailsLable = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        priceForMonthLable = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Student To Class");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        cassNameLable.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cassNameLable.setText("Class name comes hear");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setText("Class :");

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setText("Teacher :");

        teacherNameLable.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        teacherNameLable.setText("Teacher name comes hear");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setText("Student :");

        studentDetailsLable.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        studentDetailsLable.setText("Student name comes hear");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setText("Price for Month :");

        priceForMonthLable.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        priceForMonthLable.setText("Class Moth Price Comes Hear.");

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setText("Paymet :");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFormattedTextField1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jFormattedTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextField1KeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jButton1.setText("Register For Class");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cassNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teacherNameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFormattedTextField1))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(priceForMonthLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(studentDetailsLable, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel3)
                    .addContainerGap(615, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(cassNameLable)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(teacherNameLable))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(studentDetailsLable))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(priceForMonthLable, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(jLabel3)
                    .addContainerGap(226, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField1KeyReleased

        if (Double.parseDouble(jFormattedTextField1.getText()) == classPrice) {
            jButton1.setEnabled(true);
        }

    }//GEN-LAST:event_jFormattedTextField1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int classTableRow = classPanel.jTable2.getSelectedRow();

        // Get the current date
        LocalDate currentDate = LocalDate.now();
        // Get the month 
        String month = currentDate.getMonth().getDisplayName(TextStyle.FULL, Locale.ENGLISH);

        String quary = "SELECT * FROM `student_has_class` WHERE `student_has_class`.`Class_ClassNo` = ? AND `student_has_class`.`Student_Sno` = ?";

        try {
            ResultSet result = MySQL.executeSelect(quary, String.valueOf(classPanel.jTable2.getValueAt(classTableRow, 0)), studentID);

            if (result.next()) {
                if (result.getInt("student_has_class.status_id") == 2) {
                    int condition = JOptionPane.showConfirmDialog(this, "This student is alredy registerd in this class. But Status is bolocked. Do you need to active again", "Alert", JOptionPane.INFORMATION_MESSAGE);

                    if (condition == JOptionPane.OK_OPTION) {
                        String UpdateStatusQuary = "UPDATE `student_has_class` SET `student_has_class`.`status_id` = '1' WHERE `student_has_class`.`id` = ?";
                        try {
                            MySQL.executeUpdate(UpdateStatusQuary, result.getString("student_has_class.id"));
                        } catch (SQLException e) {
                            if (e.getMessage().startsWith("Creating")) {
                                Notifications.getInstance().setJFrame(SplashWindow.spalshWindow);
                                Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.BOTTOM_RIGHT, 10000, "Student Re-add Add To Class.");
                            } else {
                                Notifications.getInstance().setJFrame(SplashWindow.spalshWindow);
                                Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.BOTTOM_RIGHT, 10000, "Student Activating fail. :" + e.getMessage());
                            }
                            e.printStackTrace();
                        }
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "This student alredy registerd to this class.", "Warnning", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                String addStudentClassQuary = "INSERT INTO `student_has_class` (`Class_ClassNo`,`status_id`,`Student_Sno`) VALUES (?,'1',?)";

                String searchMonthQuary = "SELECT * FROM `month` WHERE `month`.`month` LIKE ?";

                String addToInvoiceTable = "INSERT INTO `invoice` (`datetime`,`Value`,`month_id`,`Student_has_Class_id`) VALUES (?,?,?,?)";

                int id = MySQL.executeUpdate(addStudentClassQuary, classPanel.jTable2.getValueAt(classTableRow, 0), studentID);

                ResultSet monthResults = MySQL.executeSelect(searchMonthQuary, month);

                if (monthResults.next()) {

                    Date date = new Date();
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:MM:ss");

                    MySQL.executeUpdate(addToInvoiceTable, sdf.format(date), Double.parseDouble(jFormattedTextField1.getText()), monthResults.getString("month.id"), id);

                    Notifications.getInstance().setJFrame(SplashWindow.spalshWindow);
                    Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.BOTTOM_RIGHT, 10000, "Student Registerd To Tha Class.");

                    this.dispose();

                } else {
                    JOptionPane.showMessageDialog(this, "Something vent wrong. please try again.", "Error", JOptionPane.ERROR_MESSAGE);
                }

            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cassNameLable;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel priceForMonthLable;
    private javax.swing.JLabel studentDetailsLable;
    private javax.swing.JLabel teacherNameLable;
    // End of variables declaration//GEN-END:variables
}
